/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import controlador.ConInformes;
import controlador.ConProducto;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author alfon
 */
public class ActualizarStockMasivo extends javax.swing.JFrame {

    /** Creates new form ObtenerArchivoStockMasivo */
    public ActualizarStockMasivo() {
        Image icon = Toolkit.getDefaultToolkit().getImage("src\\img\\coffee-heart-original.png");  
        this.setIconImage(icon);
        this.setTitle("Pili's Coffee POS Software | Obtener archivo stock masivo");        
        initComponents();
        txt_filtro.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rb_total = new javax.swing.JRadioButton();
        rb_filtrado = new javax.swing.JRadioButton();
        txt_filtro = new javax.swing.JTextField();
        btn_generarReporte = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btn_subir = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(625, 690));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(230, 204, 178));
        jPanel1.setPreferredSize(new java.awt.Dimension(625, 690));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 85, 57));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OBTENER EXCEL DE CARGA");

        rb_total.setBackground(new java.awt.Color(230, 204, 178));
        buttonGroup1.add(rb_total);
        rb_total.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        rb_total.setForeground(new java.awt.Color(127, 85, 57));
        rb_total.setSelected(true);
        rb_total.setText("Archivo de stock general");
        rb_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_totalActionPerformed(evt);
            }
        });

        rb_filtrado.setBackground(new java.awt.Color(230, 204, 178));
        buttonGroup1.add(rb_filtrado);
        rb_filtrado.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        rb_filtrado.setForeground(new java.awt.Color(127, 85, 57));
        rb_filtrado.setText("Filtrar por palabra clave");
        rb_filtrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_filtradoActionPerformed(evt);
            }
        });

        txt_filtro.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        btn_generarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/custom buttons/generarexcel_solid.png"))); // NOI18N
        btn_generarReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_generarReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_generarReporteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_generarReporteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_generarReporteMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 85, 57));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ACTUALIZACIÓN MASIVA");

        btn_subir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/custom buttons/subirarchivocarga_solid.png"))); // NOI18N
        btn_subir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_subirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_subirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_subirMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_subirMouseReleased(evt);
            }
        });

        ProgressBar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ProgressBar.setForeground(new java.awt.Color(127, 85, 57));
        ProgressBar.setBorderPainted(false);
        ProgressBar.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb_filtrado)
                                    .addComponent(rb_total)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(btn_generarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                            .addComponent(ProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(btn_subir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(rb_total)
                .addGap(18, 18, 18)
                .addComponent(rb_filtrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btn_generarReporte)
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_subir)
                .addGap(37, 37, 37)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_totalActionPerformed
        filtroEditable();
    }//GEN-LAST:event_rb_totalActionPerformed

    private void rb_filtradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_filtradoActionPerformed
        filtroEditable();
    }//GEN-LAST:event_rb_filtradoActionPerformed

    private void btn_generarReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generarReporteMouseEntered
        ImageIcon botonClick = new ImageIcon(getClass().getResource("/img/custom buttons/generarexcel_click.png"));
        btn_generarReporte.setIcon(botonClick);
    }//GEN-LAST:event_btn_generarReporteMouseEntered

    private void btn_generarReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generarReporteMouseExited
        ImageIcon botonClick = new ImageIcon(getClass().getResource("/img/custom buttons/generarexcel_solid.png"));
        btn_generarReporte.setIcon(botonClick);
    }//GEN-LAST:event_btn_generarReporteMouseExited

    private void btn_generarReporteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generarReporteMousePressed
        ImageIcon botonClick = new ImageIcon(getClass().getResource("/img/custom buttons/generarexcel_click.png"));
        btn_generarReporte.setIcon(botonClick);
        ConProducto cProducto = new ConProducto();
        if(rb_total.isSelected()){
            cProducto.excelCargaStockMasivo("");
        }
        else if(rb_filtrado.isSelected()){
            String filtro = txt_filtro.getText();
            if(filtro.equals("")){
                JOptionPane.showMessageDialog(this, "Debe llenar el campo de texto para aplicar un filtro", "No hay filtro", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                cProducto.excelCargaStockMasivo(filtro);
            }
        }
    }//GEN-LAST:event_btn_generarReporteMousePressed

    private void btn_generarReporteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generarReporteMouseReleased
        ImageIcon botonClick = new ImageIcon(getClass().getResource("/img/custom buttons/generarexcel_solid.png"));
        btn_generarReporte.setIcon(botonClick);
    }//GEN-LAST:event_btn_generarReporteMouseReleased

    private void btn_subirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subirMouseEntered
        ImageIcon botonClick = new ImageIcon(getClass().getResource("/img/custom buttons/subirarchivocarga_click.png"));
        btn_subir.setIcon(botonClick);
    }//GEN-LAST:event_btn_subirMouseEntered

    private void btn_subirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subirMouseExited
        ImageIcon botonClick = new ImageIcon(getClass().getResource("/img/custom buttons/subirarchivocarga_solid.png"));
        btn_subir.setIcon(botonClick);
    }//GEN-LAST:event_btn_subirMouseExited

    private void btn_subirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subirMousePressed
        ImageIcon botonClick = new ImageIcon(getClass().getResource("/img/custom buttons/subirarchivocarga_click.png"));
        btn_subir.setIcon(botonClick);
        String ruta =System.getProperty("user.home")+"/Desktop/Carga masiva/Actualizacion stock masivo/";
        JFileChooser jf = new JFileChooser(ruta);
        jf.updateUI();

        jf.showOpenDialog(this);
        File archivo = jf.getSelectedFile();
        if(archivo != null){
            if(archivo.toString().contains("Stock masivo.xlsx")){
                int confirmar = JOptionPane.showConfirmDialog(this, "Este proceso puede tardar unos minutos, ¿desea continuar?", "Confirmar carga", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(confirmar == 0){
                    ConProducto cProducto = new ConProducto();
                    cProducto.actualizacionMasiva(archivo, ProgressBar, this);
                }
            }

        }
        ProgressBar.setVisible(true);
        botonClick = new ImageIcon(getClass().getResource("/img/custom buttons/subirarchivocarga_solid.png"));
        btn_subir.setIcon(botonClick);
    }//GEN-LAST:event_btn_subirMousePressed

    private void btn_subirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_subirMouseReleased
        ImageIcon botonClick = new ImageIcon(getClass().getResource("/img/custom buttons/subirarchivocarga_solid.png"));
        btn_subir.setIcon(botonClick);
    }//GEN-LAST:event_btn_subirMouseReleased
   
    private void filtroEditable(){
        if(rb_filtrado.isSelected()){
            txt_filtro.setEnabled(true);
        }
        else{
            txt_filtro.setEnabled(false);
            txt_filtro.setText("");
        } 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarStockMasivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarStockMasivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarStockMasivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarStockMasivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarStockMasivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JLabel btn_generarReporte;
    private javax.swing.JLabel btn_subir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rb_filtrado;
    private javax.swing.JRadioButton rb_total;
    private javax.swing.JTextField txt_filtro;
    // End of variables declaration//GEN-END:variables

}
