/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.ConProducto;
import db.Conexion;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;  
import java.nio.file.Files;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import javax.swing.JOptionPane;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.plaf.basic.BasicProgressBarUI;

/**
 *
 * @author alfon
 */
public class CargaMasiva extends javax.swing.JFrame {

    public static final Conexion CONEXION = new Conexion();
    
    public CargaMasiva() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("src\\img\\coffee-heart-original.png");  
        this.setIconImage(icon);
        this.setTitle("Pili's Coffee POS Software | Carga masiva de productos");
        InternalFrame.setVisible(false);
        ProgressBar.setVisible(false);
        ProgressBar.setUI(new BasicProgressBarUI() {
            protected Color getSelectionBackground() { return Color.black; };
            protected Color getSelectionForeground() { return Color.white; };
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_descargaPlantilla = new javax.swing.JButton();
        btn_subirArchivo = new javax.swing.JButton();
        InternalFrame = new javax.swing.JInternalFrame();
        FIleChooser = new javax.swing.JFileChooser();
        ProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(224, 177, 203));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 28)); // NOI18N
        jLabel1.setText("Carga masiva de productos");

        btn_descargaPlantilla.setBackground(new java.awt.Color(94, 84, 142));
        btn_descargaPlantilla.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_descargaPlantilla.setForeground(new java.awt.Color(255, 255, 255));
        btn_descargaPlantilla.setText("Descargar plantilla");
        btn_descargaPlantilla.setFocusPainted(false);
        btn_descargaPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descargaPlantillaActionPerformed(evt);
            }
        });

        btn_subirArchivo.setBackground(new java.awt.Color(94, 84, 142));
        btn_subirArchivo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_subirArchivo.setForeground(new java.awt.Color(255, 255, 255));
        btn_subirArchivo.setText("Subir archivo de carga");
        btn_subirArchivo.setFocusPainted(false);
        btn_subirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subirArchivoActionPerformed(evt);
            }
        });

        InternalFrame.setIconifiable(true);
        InternalFrame.setTitle("Seleccione el archivo de carga masiva");
        InternalFrame.setVisible(true);
        InternalFrame.getContentPane().setLayout(new java.awt.CardLayout());

        FIleChooser.setCurrentDirectory(new java.io.File("C:\\Users\\alfon\\Desktop\\PilisCoffePOS\\Carga masiva"));
        FIleChooser.setInheritsPopupMenu(true);
        FIleChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIleChooserActionPerformed(evt);
            }
        });
        InternalFrame.getContentPane().add(FIleChooser, "card2");

        ProgressBar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ProgressBar.setForeground(new java.awt.Color(159, 134, 192));
        ProgressBar.setStringPainted(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(772, 772, 772))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ProgressBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_descargaPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btn_subirArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(InternalFrame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_descargaPlantilla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_subirArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(InternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_descargaPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descargaPlantillaActionPerformed
        String  rutaPlantilla = "src\\\\Plantillas\\\\Carga masiva productos.xlsx";   
        String rutaDescarga =System.getProperty("user.home")+"\\Desktop\\PilisCoffePOS\\Carga masiva\\"; 
        File archivoCopia = new File(rutaPlantilla);       
        File rutaFinalCopia = new File(rutaDescarga+archivoCopia.getName());  
        try{
            Files.copy(archivoCopia.toPath(), rutaFinalCopia.toPath(),REPLACE_EXISTING);  
            JOptionPane.showMessageDialog(this, "Se creó una copia", "Copia realizada", JOptionPane.INFORMATION_MESSAGE);
            Desktop.getDesktop().open(new File(rutaDescarga));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "No se pudo obtener la copia", "Copia fallida", JOptionPane.WARNING_MESSAGE);  
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btn_descargaPlantillaActionPerformed

    private void btn_subirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subirArchivoActionPerformed
        InternalFrame.setVisible(true);
        ProgressBar.setVisible(true);
    }//GEN-LAST:event_btn_subirArchivoActionPerformed

    private void FIleChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIleChooserActionPerformed
        if(!evt.getActionCommand().equals("CancelSelection")){   
            String archivoSeleccionado = FIleChooser.getSelectedFile().toString();
            if(archivoSeleccionado.contains("Carga masiva productos.xlsx")){
                File archivoCarga = FIleChooser.getSelectedFile();    
                int confirmar = JOptionPane.showConfirmDialog(this, "Este proceso puede tardar unos minutos, ¿desea continuar?", "Confirmar carga", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(confirmar == 0){  
                    if(CONEXION.isNetworkOnline()){
                        ConProducto cProducto = new ConProducto();
                        cProducto.cargaMasiva(archivoCarga, ProgressBar, InternalFrame);

                    }
                    else JOptionPane.showMessageDialog(this, "No hay acceso al servidor en estos momentos, no se puede comunicar con la base de datos, vuelva a intentarlo cuando tenga una conexion a internet", "Carga fallida", JOptionPane.WARNING_MESSAGE);  


                }    
            }  
            else JOptionPane.showMessageDialog(this, "El archivo debe llamarse 'Carga masiva productos.xlsx'", "Carga fallida", JOptionPane.WARNING_MESSAGE);  
                
                        
            
        }
        else {
            InternalFrame.dispose();
            ProgressBar.setVisible(false);
        }
        
    }//GEN-LAST:event_FIleChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargaMasiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargaMasiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargaMasiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargaMasiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargaMasiva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser FIleChooser;
    private javax.swing.JInternalFrame InternalFrame;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton btn_descargaPlantilla;
    private javax.swing.JButton btn_subirArchivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}


