package vista;
import controlador.ConProducto;
import java.awt.*;  
import java.util.ArrayList;
import modelo.Producto;


public class Inicio extends javax.swing.JFrame {
    

    
        
    public Inicio() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("src\\img\\coffee-heart-original.png");  
        this.setIconImage(icon);
        this.setTitle("Pili's Coffee POS Software | Inicio");                        
    }
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        mb_barraPrincipal = new javax.swing.JMenuBar();
        menu_ventas = new javax.swing.JMenu();
        mi_nuevaVenta = new javax.swing.JMenuItem();
        mi_consultarPrecio = new javax.swing.JMenuItem();
        menu_inventario = new javax.swing.JMenu();
        mi_editarStockPrecio = new javax.swing.JMenuItem();
        mi_ingresarProducto = new javax.swing.JMenuItem();
        mi_cargaMasiva = new javax.swing.JMenuItem();
        menu_informes = new javax.swing.JMenu();
        mi_infVentaDiario = new javax.swing.JMenuItem();
        mi_infVentaPeriodo = new javax.swing.JMenuItem();
        mi_infVerStock = new javax.swing.JMenuItem();
        mi_infStockNegativo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(224, 177, 203));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(35, 25, 66));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pili's Coffee POS");

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coffee-heart-original.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mb_barraPrincipal.setBackground(new java.awt.Color(159, 134, 192));
        mb_barraPrincipal.setBorder(null);
        mb_barraPrincipal.setForeground(new java.awt.Color(35, 25, 66));

        menu_ventas.setForeground(new java.awt.Color(35, 25, 66));
        menu_ventas.setText("Ventas");
        menu_ventas.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N
        menu_ventas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mi_nuevaVenta.setBackground(new java.awt.Color(159, 134, 192));
        mi_nuevaVenta.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        mi_nuevaVenta.setForeground(new java.awt.Color(35, 25, 66));
        mi_nuevaVenta.setLabel("Nueva venta");
        mi_nuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_nuevaVentaActionPerformed(evt);
            }
        });
        menu_ventas.add(mi_nuevaVenta);

        mi_consultarPrecio.setBackground(new java.awt.Color(159, 134, 192));
        mi_consultarPrecio.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        mi_consultarPrecio.setForeground(new java.awt.Color(35, 25, 66));
        mi_consultarPrecio.setText("Consultar precio");
        mi_consultarPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_consultarPrecioActionPerformed(evt);
            }
        });
        menu_ventas.add(mi_consultarPrecio);

        mb_barraPrincipal.add(menu_ventas);

        menu_inventario.setForeground(new java.awt.Color(35, 25, 66));
        menu_inventario.setText("Inventario");
        menu_inventario.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N

        mi_editarStockPrecio.setBackground(new java.awt.Color(159, 134, 192));
        mi_editarStockPrecio.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        mi_editarStockPrecio.setForeground(new java.awt.Color(35, 25, 66));
        mi_editarStockPrecio.setText("Aumentar stock/Actualizar precio");
        mi_editarStockPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_editarStockPrecioActionPerformed(evt);
            }
        });
        menu_inventario.add(mi_editarStockPrecio);

        mi_ingresarProducto.setBackground(new java.awt.Color(159, 134, 192));
        mi_ingresarProducto.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        mi_ingresarProducto.setForeground(new java.awt.Color(35, 25, 66));
        mi_ingresarProducto.setText("Ingresar producto");
        mi_ingresarProducto.setToolTipText("");
        mi_ingresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ingresarProductoActionPerformed(evt);
            }
        });
        menu_inventario.add(mi_ingresarProducto);

        mi_cargaMasiva.setBackground(new java.awt.Color(159, 134, 192));
        mi_cargaMasiva.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        mi_cargaMasiva.setForeground(new java.awt.Color(35, 25, 66));
        mi_cargaMasiva.setText("Carga masiva productos");
        mi_cargaMasiva.setToolTipText("");
        mi_cargaMasiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_cargaMasivaActionPerformed(evt);
            }
        });
        menu_inventario.add(mi_cargaMasiva);

        mb_barraPrincipal.add(menu_inventario);

        menu_informes.setForeground(new java.awt.Color(35, 25, 66));
        menu_informes.setText("Informes");
        menu_informes.setFont(new java.awt.Font("Georgia", 0, 20)); // NOI18N

        mi_infVentaDiario.setBackground(new java.awt.Color(159, 134, 192));
        mi_infVentaDiario.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        mi_infVentaDiario.setForeground(new java.awt.Color(35, 25, 66));
        mi_infVentaDiario.setText("Informe venta diario");
        menu_informes.add(mi_infVentaDiario);

        mi_infVentaPeriodo.setBackground(new java.awt.Color(159, 134, 192));
        mi_infVentaPeriodo.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        mi_infVentaPeriodo.setForeground(new java.awt.Color(35, 25, 66));
        mi_infVentaPeriodo.setText("Informe venta por periodo");
        menu_informes.add(mi_infVentaPeriodo);

        mi_infVerStock.setBackground(new java.awt.Color(159, 134, 192));
        mi_infVerStock.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        mi_infVerStock.setForeground(new java.awt.Color(35, 25, 66));
        mi_infVerStock.setText("Ver Stock");
        mi_infVerStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_infVerStockActionPerformed(evt);
            }
        });
        menu_informes.add(mi_infVerStock);

        mi_infStockNegativo.setBackground(new java.awt.Color(159, 134, 192));
        mi_infStockNegativo.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        mi_infStockNegativo.setForeground(new java.awt.Color(35, 25, 66));
        mi_infStockNegativo.setText("Informe diario stock negativo");
        mi_infStockNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_infStockNegativoActionPerformed(evt);
            }
        });
        menu_informes.add(mi_infStockNegativo);

        mb_barraPrincipal.add(menu_informes);

        setJMenuBar(mb_barraPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mi_nuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_nuevaVentaActionPerformed
        ConProducto cProducto = new ConProducto();
        ArrayList<Producto> listado = cProducto.listarProductos();
        NuevaVenta ventana = new NuevaVenta(listado);
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_nuevaVentaActionPerformed

    private void mi_ingresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ingresarProductoActionPerformed
        IngresarProducto ventana = new IngresarProducto();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_ingresarProductoActionPerformed

    private void mi_cargaMasivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cargaMasivaActionPerformed
        CargaMasiva ventana = new CargaMasiva();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_cargaMasivaActionPerformed

    private void mi_editarStockPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_editarStockPrecioActionPerformed
        EditarStockPrecio ventana = new EditarStockPrecio();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_editarStockPrecioActionPerformed

    private void mi_consultarPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_consultarPrecioActionPerformed
        ConsultarPrecio ventana = new ConsultarPrecio();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_consultarPrecioActionPerformed

    private void mi_infVerStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_infVerStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_infVerStockActionPerformed

    private void mi_infStockNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_infStockNegativoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mi_infStockNegativoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JMenuBar mb_barraPrincipal;
    private javax.swing.JMenu menu_informes;
    private javax.swing.JMenu menu_inventario;
    private javax.swing.JMenu menu_ventas;
    private javax.swing.JMenuItem mi_cargaMasiva;
    private javax.swing.JMenuItem mi_consultarPrecio;
    private javax.swing.JMenuItem mi_editarStockPrecio;
    private javax.swing.JMenuItem mi_infStockNegativo;
    private javax.swing.JMenuItem mi_infVentaDiario;
    private javax.swing.JMenuItem mi_infVentaPeriodo;
    private javax.swing.JMenuItem mi_infVerStock;
    private javax.swing.JMenuItem mi_ingresarProducto;
    private javax.swing.JMenuItem mi_nuevaVenta;
    // End of variables declaration//GEN-END:variables
}
