package vista;

import controlador.ConColores;
import controlador.ConInformes;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import modelo.PaletaColor;

/**
 *
 * @author alfon
 */
public class ReporteDiario extends javax.swing.JFrame {

    String global_dia,global_mes,global_anio;
    private static final ConColores cColor = new ConColores();  
    JFrame mainWindow;
    int xMouse, yMouse; 
    PaletaColor paleta = cColor.paletaActiva();
    //COLORES    
    Color BackgroundColor = paleta.getBackground();
    Color PanelColor = paleta.getPanel();
    Color mouseEnterPanelColor = paleta.getMouseEnter();
    Color mouseExitPanelColor = PanelColor;
    Color mouseClickPanelColor = paleta.getMouseClick();
    Color textColor = mouseEnterPanelColor;  
    
    public ReporteDiario() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage("src\\img\\coffee-heart-original.png");  
        this.setIconImage(icon);
        this.setTitle("Reporte de venta diario");     
        Date date = Calendar.getInstance().getTime();

        DateFormat formatter = new SimpleDateFormat("dd-MM-yyyy");
        String today = formatter.format(date);
        String dia = today.split("-")[0];
        String mes = today.split("-")[1];
        String anio = today.split("-")[2];
        
        global_dia = dia;
        global_mes = mes;
        global_anio = anio;
        
        txt_dia.setText(dia);
        txt_anio.setText(anio);
        asignar_mes(mes);
        
        //COLORES
        PanelFechaReporte.setBorder(BorderFactory.createTitledBorder(null, "Fecha de reporte", TitledBorder.CENTER, TitledBorder.TOP, new Font("Roboto",Font.BOLD,24), textColor));
        Background.setBackground(BackgroundColor);
        PanelFechaReporte.setBackground(BackgroundColor);
        txt_tituloVentana.setForeground(textColor);
        MinPanel.setBackground(BackgroundColor);
        ClosePanel.setBackground(BackgroundColor);
        slash1.setForeground(textColor);
        slash2.setForeground(textColor);
        btn_crearReporte.setBackground(PanelColor);
    }

    private void asignar_mes(String mes){
        switch(mes){
            case "01":
                cb_mes.setSelectedIndex(0);
                break;
            case "02":
                cb_mes.setSelectedIndex(1);
                break;
            case "03":
                cb_mes.setSelectedIndex(2);
                break;
            case "04":
                cb_mes.setSelectedIndex(3);
                break;
            case "05":
                cb_mes.setSelectedIndex(4);
                break;
            case "06":
                cb_mes.setSelectedIndex(5);
                break;
            case "07":
                cb_mes.setSelectedIndex(6);
                break;
            case "08":
                cb_mes.setSelectedIndex(7);
                break;
            case "09":
                cb_mes.setSelectedIndex(8);
                break;
            case "10":
                cb_mes.setSelectedIndex(9);
                break;
            case "11":
                cb_mes.setSelectedIndex(10);
                break;
            case "12":
                cb_mes.setSelectedIndex(11);                
                break;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        PanelFechaReporte = new javax.swing.JPanel();
        txt_dia = new javax.swing.JTextField();
        cb_mes = new javax.swing.JComboBox<>();
        txt_anio = new javax.swing.JTextField();
        slash1 = new javax.swing.JLabel();
        slash2 = new javax.swing.JLabel();
        txt_tituloVentana = new javax.swing.JLabel();
        ClosePanel = new javax.swing.JPanel();
        txt_close = new javax.swing.JLabel();
        MinPanel = new javax.swing.JPanel();
        txt_minimize = new javax.swing.JLabel();
        btn_crearReporte = new javax.swing.JPanel();
        txt_crearReporte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(230, 204, 178));
        Background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFechaReporte.setBackground(new java.awt.Color(230, 204, 178));
        PanelFechaReporte.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 85, 57), 1, true), "Fecha de reporte", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18), new java.awt.Color(127, 85, 57))); // NOI18N
        PanelFechaReporte.setForeground(new java.awt.Color(127, 85, 57));
        PanelFechaReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_dia.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txt_dia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_dia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_dia.setPreferredSize(new java.awt.Dimension(2, 33));
        txt_dia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_diaFocusLost(evt);
            }
        });
        txt_dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_diaKeyTyped(evt);
            }
        });
        PanelFechaReporte.add(txt_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 55, 54, -1));

        cb_mes.setFont(new java.awt.Font("Roboto Thin", 1, 22)); // NOI18N
        cb_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        cb_mes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PanelFechaReporte.add(cb_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 55, -1, -1));

        txt_anio.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        txt_anio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_anio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txt_anio.setPreferredSize(new java.awt.Dimension(2, 33));
        txt_anio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_anioFocusLost(evt);
            }
        });
        txt_anio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_anioKeyTyped(evt);
            }
        });
        PanelFechaReporte.add(txt_anio, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 55, 90, -1));

        slash1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        slash1.setText("/");
        PanelFechaReporte.add(slash1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 51, -1, -1));

        slash2.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        slash2.setText("/");
        PanelFechaReporte.add(slash2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 51, -1, -1));

        Background.add(PanelFechaReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 490, 130));

        txt_tituloVentana.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txt_tituloVentana.setText("  REPORTE DE VENTA DIARIA");
        txt_tituloVentana.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                txt_tituloVentanaMouseDragged(evt);
            }
        });
        txt_tituloVentana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_tituloVentanaMousePressed(evt);
            }
        });
        Background.add(txt_tituloVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 40));

        ClosePanel.setBackground(new java.awt.Color(255, 255, 153));
        ClosePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ClosePanel.setPreferredSize(new java.awt.Dimension(35, 35));

        txt_close.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        txt_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_close.setText("X");
        txt_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_closeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_closeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout ClosePanelLayout = new javax.swing.GroupLayout(ClosePanel);
        ClosePanel.setLayout(ClosePanelLayout);
        ClosePanelLayout.setHorizontalGroup(
            ClosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClosePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ClosePanelLayout.setVerticalGroup(
            ClosePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClosePanelLayout.createSequentialGroup()
                .addComponent(txt_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Background.add(ClosePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 40, 40));

        MinPanel.setBackground(new java.awt.Color(255, 255, 153));
        MinPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MinPanel.setPreferredSize(new java.awt.Dimension(35, 35));

        txt_minimize.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        txt_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_minimize.setText("_");
        txt_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txt_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_minimizeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_minimizeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_minimizeMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout MinPanelLayout = new javax.swing.GroupLayout(MinPanel);
        MinPanel.setLayout(MinPanelLayout);
        MinPanelLayout.setHorizontalGroup(
            MinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_minimize, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        MinPanelLayout.setVerticalGroup(
            MinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_minimize, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        Background.add(MinPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 40, 40));

        btn_crearReporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_crearReporte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txt_crearReporte.setFont(new java.awt.Font("Roboto", 0, 21)); // NOI18N
        txt_crearReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_crearReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/createPdf.png"))); // NOI18N
        txt_crearReporte.setText("GENERAR REPORTE");
        txt_crearReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_crearReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_crearReporteMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_crearReporteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_crearReporteMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout btn_crearReporteLayout = new javax.swing.GroupLayout(btn_crearReporte);
        btn_crearReporte.setLayout(btn_crearReporteLayout);
        btn_crearReporteLayout.setHorizontalGroup(
            btn_crearReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_crearReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );
        btn_crearReporteLayout.setVerticalGroup(
            btn_crearReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt_crearReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
        );

        Background.add(btn_crearReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 240, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_diaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_diaKeyTyped
        txt_dia.setTransferHandler(null);
        maxCharacter(2, txt_dia, evt);
        onlyNumberField(evt);
    }//GEN-LAST:event_txt_diaKeyTyped

    private void txt_anioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_anioKeyTyped
        txt_anio.setTransferHandler(null);
        maxCharacter(4, txt_anio, evt);        
        onlyNumberField(evt);
        
    }//GEN-LAST:event_txt_anioKeyTyped

    private void txt_diaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_diaFocusLost
        diaValido(txt_dia);
        if(Integer.parseInt(txt_dia.getText())<10){
            txt_dia.setText("0"+Integer.parseInt(txt_dia.getText()));
        }
    }//GEN-LAST:event_txt_diaFocusLost

    private void txt_anioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_anioFocusLost
        anioValido(txt_anio);
    }//GEN-LAST:event_txt_anioFocusLost

    private void txt_tituloVentanaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tituloVentanaMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_txt_tituloVentanaMouseDragged

    private void txt_tituloVentanaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tituloVentanaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_txt_tituloVentanaMousePressed

    private void txt_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_closeMouseEntered
        ClosePanel.setBackground(Color.RED);
        txt_close.setForeground(Color.WHITE);
    }//GEN-LAST:event_txt_closeMouseEntered

    private void txt_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_closeMouseExited
        ClosePanel.setBackground(BackgroundColor);
        txt_close.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_closeMouseExited

    private void txt_closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_closeMousePressed
        Color DarkRed = new Color(146, 55, 77);
        ClosePanel.setBackground(DarkRed);
        txt_close.setForeground(Color.WHITE);
        this.dispose();
    }//GEN-LAST:event_txt_closeMousePressed

    private void txt_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_minimizeMouseEntered
        MinPanel.setBackground(mouseEnterPanelColor);
        txt_minimize.setForeground(Color.WHITE);
    }//GEN-LAST:event_txt_minimizeMouseEntered

    private void txt_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_minimizeMouseExited
        MinPanel.setBackground(BackgroundColor);
        txt_minimize.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_minimizeMouseExited

    private void txt_minimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_minimizeMousePressed
        MinPanel.setBackground(mouseClickPanelColor);
        txt_minimize.setForeground(Color.WHITE);
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_txt_minimizeMousePressed

    private void txt_minimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_minimizeMouseReleased
        MinPanel.setBackground(BackgroundColor);
        txt_minimize.setForeground(Color.BLACK);
    }//GEN-LAST:event_txt_minimizeMouseReleased

    private void txt_crearReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_crearReporteMouseEntered
        btn_crearReporte.setBackground(mouseEnterPanelColor);
    }//GEN-LAST:event_txt_crearReporteMouseEntered

    private void txt_crearReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_crearReporteMouseExited
        btn_crearReporte.setBackground(mouseExitPanelColor);
    }//GEN-LAST:event_txt_crearReporteMouseExited

    private void txt_crearReporteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_crearReporteMouseReleased
        if(btn_crearReporte.contains(evt.getPoint())) btn_crearReporte.setBackground(mouseEnterPanelColor);
        else btn_crearReporte.setBackground(mouseExitPanelColor);
    }//GEN-LAST:event_txt_crearReporteMouseReleased

    private void txt_crearReporteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_crearReporteMousePressed
        if(evt.getButton() == 1){    
            ConInformes informe = new ConInformes();
            txt_diaFocusLost(null);
            String mes;
            if((cb_mes.getSelectedIndex()+1)<10){
                mes = "0"+String.valueOf(cb_mes.getSelectedIndex()+1);
            }
            else{
               mes = String.valueOf(cb_mes.getSelectedIndex()+1); 
            }
            String fecha = txt_anio.getText()+"-"+mes +"-"+txt_dia.getText();


            informe.informeVentaPeriodo(fecha, fecha); 
        }
    }//GEN-LAST:event_txt_crearReporteMousePressed
    
    private void onlyNumberField(java.awt.event.KeyEvent evt){
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
        }
    }
    
    private void maxCharacter(int cantidad, JTextField campo, java.awt.event.KeyEvent evt){
        if(campo.getText().length() == cantidad){
            campo.setText("");
        }
    }
    
    private void diaValido(JTextField campo){
        int intDia = Integer.parseInt(campo.getText());
        if(intDia >= 31){
            campo.setText(global_dia);
        }
    }
    
    private void anioValido(JTextField campo){
        int intAnio = Integer.parseInt(campo.getText());
        int maxAnio = Integer.parseInt(global_anio);
        if(intAnio < 2022 || intAnio > maxAnio){
            campo.setText(global_anio);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteDiario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteDiario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel ClosePanel;
    private javax.swing.JPanel MinPanel;
    private javax.swing.JPanel PanelFechaReporte;
    private javax.swing.JPanel btn_crearReporte;
    private javax.swing.JComboBox<String> cb_mes;
    private javax.swing.JLabel slash1;
    private javax.swing.JLabel slash2;
    private javax.swing.JTextField txt_anio;
    private javax.swing.JLabel txt_close;
    private javax.swing.JLabel txt_crearReporte;
    private javax.swing.JTextField txt_dia;
    private javax.swing.JLabel txt_minimize;
    private javax.swing.JLabel txt_tituloVentana;
    // End of variables declaration//GEN-END:variables
}
